config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :memberships
  resources :beer_clubs
  resources :users do
    post 'toggle_activity', on: :member
  end
  get 'beerlist', to:'beers#list'
  get 'brewerylist', to:'breweries#list'
  root 'breweries#index'
  get 'kaikki_bisset', to: 'beers#index'
  # get 'ratings', to: 'ratings#index'
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  get 'signup', to: 'users#new'
  # get 'ratings/new', to:'ratings#new'
  # post 'ratings', to: 'ratings#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  get 'places', to: 'places#index'
  post 'places', to:'places#search'
  resources :places, only: [:index, :show]
end

app/models/user.rb
class User < ApplicationRecord
  include RatingAverage
  validates :username, uniqueness: true
  validates :username, length: { minimum: 3 }
  validates :username, length: { maximum: 30 }
  validates :password, format: { with: /\A^(?=.*[a-zA-Z])(?=.*[0-9]).{4,}\z/, message: "must be atleast 4 characters long and contain a number and big letter." }
  has_many :ratings, dependent: :destroy
  has_many :beers, through: :ratings
  has_many :memberships
  has_many :beer_clubs, through: :memberships
  has_secure_password

  def favorite_beer
    return nil if ratings.empty?

    ratings.order(score: :desc).limit(1).first.beer
  end

  def average_of(ratings)
    ratings.sum(&:score).to_f / ratings.count
  end

  def favorite_style
    return nil if ratings.empty?

    style_ratings = ratings.group_by{ |r| r.beer.style }
    averages = style_ratings.map do |style, ratings|
      { style: style.name, score: average_of(ratings) }
    end

    averages.max_by{ |r| r[:score] }[:style]
  end

  def self.top(n)
    users = User.all.sort_by{ |u| u.ratings.count * -1 }
    users.take(n)
  end

  def favorite_brewery
    return nil if ratings.empty?

    style_ratings = ratings.group_by{ |r| r.beer.brewery }
    averages = style_ratings.map do |brewery, ratings|
      { brewery: brewery, score: average_of(ratings) }
    end

    averages.max_by{ |r| r[:score] }[:brewery]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.includes(:beers, :ratings).all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  def toggle_activity
    user = User.find(params[:id])
    user.update_attribute :closed, (not user.closed)
  
    new_status = user.closed? ? "closed" : "opened"
  
    redirect_to user, notice:"account of #{user.username} #{new_status}"
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if user_params[:username].nil? && current_user == @user && @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if @user == current_user
      @user.destroy
      reset_session
      respond_to do |format|
        format.html { redirect_to users_url, notice: "User was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @user.new_record? %>
    <div class="field">
      <%= form.label :username %>
      <%= form.text_field :username %>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :password %><br />
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %><br />
    <%= form.password_field :password_confirmation  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Change password for <%= @user.username %></h1>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<h1>Users</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Username</th>
      <th> rated beers </th>
      <th> total ratings </th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
        <td><%= user.beers.size %></td>
        <td><%= user.ratings.size %></td>
        <td>
          <% if current_user.admin and user.closed %>
            <span class="label label-info">account frozen</span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h2>
  <%= @user.username %>
</h2>
<% if current_user && current_user.admin %>
  <% if @user.closed %>
    <span class="badge badge-info">account closed</span>
    <%= link_to "open account", toggle_activity_user_path(@user.id), method: :post, class: "btn btn-primary" %>
  <% else %>
    <%= link_to "close account", toggle_activity_user_path(@user.id), method: :post, class: "btn btn-primary" %>
  <% end %>
<% end %>

<p>
  member of:
  <% @user.beer_clubs.each do |club|%>
    <li> <%= link_to club.name, beer_club_path(club.id) %> </li>
  <% end %>
</p>

<p>
  <% if @user.ratings.empty? %>
    Has made 0 ratings
  <% else %>
    Has made <%= @user.ratings.count %> <%= "rating".pluralize(@user.ratings.count)%>, average rating <%= @user.average_rating %>
    <p>Favorite beer: <%= @user.favorite_beer.name %></p>
    <p>Favorite brewery: <%= @user.favorite_brewery.name %></p>
    <p>Preferred style: <%= @user.favorite_style %></p>
    <h2>Ratings</h2>
    <ul>
      <% @user.ratings.each do |rating| %>
        <li> <%= rating %> 
        <% if @user == current_user %>
          <%= link_to 'delete', rating_path(rating.id), method: :delete %> </li>        
        <% end %>
        </li>
      <% end %>
    </ul>
  <% end %>
</p>

<% if current_user == @user %>
  <td><%= link_to 'delete account', user_path(@user.id), method: :delete, :class=>"btn btn-danger" %></td>
  <td><%= link_to 'edit account', edit_user_path(@user.id), :class=>"btn btn-primary" %></td>
<% end %>